### ISSUE TITLE
Current screenshots missing

### ISSUE THREAD

**Issue by cweiske** [SuperTux/SuperTux.github.io#2]
The [screenshots page](https://supertuxproject.org/screenshots.html) links to large version of the images, but they are missing - at least those of the 0.4.0 version:
- https://supertuxproject.org/images/0_4_0_1.png
- https://supertuxproject.org/images/0_4_0_2.png

**Comment by maxteufel** [comment]
Thanks for reporting the issue. This was apparently an oversight when porting the pages.
